### ISSUE TITLE
problem running ppxf_kinematics_example_sdss

### ISSUE THREAD

**Issue by hlabathems** [bamford/ppxf#1]
Traceback (most recent call last):
  File "ppxf_kinematics_example_sdss.py", line 193, in <module>
    ppxf_kinematics_example_sdss()
  File "ppxf_kinematics_example_sdss.py", line 174, in ppxf_kinematics_example_sdss
    degree=12, vsyst=dv, clean=False)
  File "/Users/michaelhlabathe/Desktop/UCT/PhD/Project/Codes/Other_codes/ppxf/ppxf.py", line 861, in __init__
    mp = mpfit.mpfit(self._fitfunc, parinfo=parinfo, quiet=1, ftol=1e-4)
  File "/Users/michaelhlabathe/Desktop/UCT/PhD/Project/Codes/Other_codes/ppxf/cap_mpfit.py", line 1000, in __init__
    [self.status, fvec] = self.call(fcn, self.params, functkw)
  File "/Users/michaelhlabathe/Desktop/UCT/PhD/Project/Codes/Other_codes/ppxf/cap_mpfit.py", line 1475, in call
    [status, f] = fcn(x, fjac=fjac, **functkw)
  File "/Users/michaelhlabathe/Desktop/UCT/PhD/Project/Codes/Other_codes/ppxf/ppxf.py", line 1056, in _fitfunc
    tt = np.fft.irfft(star_rfft*losvd_rfft[:, self.component[j], k])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by AbhishekPaswan** [comment]
I also found the same error @hlabathems. Did you get your solution ?

**Comment by hlabathems** [comment]
No I didn't

**Comment by almendradelmoral** [comment]
any solution?

**Comment by magdalenahamel** [comment]
Same problem here. Any solutions?

**Comment by bamford** [comment]
Note that this is not an official repo. Closing this old issue.
